# Generated by Django 2.2.5 on 2019-11-19 17:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=20, verbose_name='Nombre de la Categoria')),
                ('Estado', models.BooleanField(default=True, verbose_name='Categoria activada / Categoria no activada')),
                ('Fecha_Creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('idLogro', models.AutoField(primary_key=True, serialize=False)),
                ('NombreLogro', models.CharField(max_length=30, verbose_name='Nombre del Logro')),
                ('ImagenLogro', models.ImageField(upload_to='', verbose_name='Imagen del Logro')),
                ('Puntaje_Minimo', models.IntegerField(verbose_name='Puntaje Minimo Requerido')),
                ('Fecha_Logro', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de logro adquirido')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['NombrePais'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('NombreUsuario', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('ClaveUsuario', models.CharField(max_length=16, verbose_name='Contraseña del Usuario')),
                ('Correo', models.EmailField(max_length=80, verbose_name='Correo del Usuario')),
                ('ImagenPerfil', models.ImageField(default=True, upload_to='', verbose_name='Imagen de perfil')),
                ('idPais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Pais')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoUsuario', models.CharField(max_length=20, verbose_name='Tipo de Usuario')),
                ('idUsuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos_Categoria',
            fields=[
                ('idPuntaje', models.AutoField(primary_key=True, serialize=False)),
                ('Puntos', models.IntegerField(verbose_name='Puntaje')),
                ('idCategoria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PuntajeUsuario',
            fields=[
                ('idPuntajeUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Puntaje_Acumulado', models.IntegerField(verbose_name='Puntaje Total')),
                ('IdPuntaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Puntos_Categoria')),
                ('idLogro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Logro')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('Respuesta1', models.CharField(max_length=100, verbose_name='Respuesta 1')),
                ('Respuesta2', models.CharField(max_length=100, verbose_name='Respuesta 2')),
                ('Respuesta3', models.CharField(max_length=100, verbose_name='Respuesta 3')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado / No Publicado')),
                ('fecha_creacion_post', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Progplay.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='logro',
            name='idPuntaje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Progplay.Puntos_Categoria'),
        ),
    ]
